<a href="https://colab.research.google.com/github/Luminary0528/Data-Science-Practice/blob/main/numpyothLibraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = [1, 2, 3, 4]

arr = np.array(a)

print("List in python : ", a)

print("Numpy Array in python :",
      arr)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


In [ ]:
print(type(a))

<class 'list'>


In [ ]:
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1,
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
sample_array = np.array([[0, 4, 2],
                         [3, 4, 5],
                         [23, 4, 2],
                         [1, 9, 34],
                         [5, 45, 8]])

print("shape of the array :",
      sample_array.shape)


shape of the array : (5, 3)


In [ ]:
import numpy as np

sample_array_1 = np.array([0, 4, 5])
sample_array_2 = np.array([0.2, 0.6, 9.2])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of the array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of the array 2 : float64


In [ ]:
import numpy as np

arr = np.array([3,4,5,5])

print("Array :",arr)

Array : [3 4 5 5]


In [ ]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [ ]:
import numpy as np

np.arange(1, 20 , 2,
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [ ]:
import numpy as np

np.linspace(3.5, 10, 3,
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

In [ ]:
import numpy as np

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[1102740331, 1699556963, 1919117682],
       [         0, 1667854964, 1630430057],
       [         0, 1768972590, 1294887280],
       [         0, 1952795950, 1769108581]], dtype=int32)

In [ ]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
import numpy as np
np.zeros([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

pow_ans = np.power(a, b)
print(pow_ans)

[                 25          1934917632        137858491849
 1152921504606846976]


In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


In [ ]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])

res = arr + 1
print(res)

[2 3 4]


In [ ]:
import numpy as np

a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [ ]:
import numpy as np
ages = np.array([12, 2, 45, 60,2])
age_group = np.array(["Adult", "Minor"])
result = np.where(ages > 18, age_group[0], age_group[1])
print(result)

['Minor' 'Minor' 'Adult' 'Adult' 'Minor']


In [ ]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


In [ ]:
import numpy as np
food_data = np.array([[0.8, 2.9, 3.9],
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([9,4,4])

caloric_matrix = caloric_values

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


In [ ]:
import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],
    [25, 27, 29, 28, 26],
    [20, 22, 24, 23, 21]
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [ ]:
import numpy as np

image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)
std = image.std(axis=0)

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


In [ ]:
import numpy as np

data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


In [ ]:
import pandas as pd
import numpy as np

ser = pd.Series()
print("Pandas Series: ", ser)

data = np.array(['g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)
print("Pandas Series:\n", ser)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: object


In [ ]:
import pandas as pd

data = [1, 2, 3, 4]

ser = pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)

print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object


In [ ]:
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])

print(ser[16])

o


In [ ]:
import pandas as pd

df = pd.read_csv("nba.csv")

ser = pd.Series(df['Name'])
data = ser.head(10)
data

FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'

In [ ]:
import pandas as pd

ser1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
ser2 = pd.Series([4, 5, 6], index=['A', 'B', 'C'])

df_sum = ser1.add(ser2)
print(df_sum)

A    5
B    7
C    9
dtype: int64


In [ ]:
import pandas as pd

ser = pd.Series([1, 2, 3, 4])
ser = ser.astype(float)
print(ser)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64


In [ ]:
import pandas as pd

lst = ['Geeks', 'For', 'Geeks', 'is',
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [ ]:
import pandas as pd

data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

df = pd.DataFrame(data)

print(df)


    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
import pandas as pd

data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data)

print(df[['Name', 'Qualification']])

     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd


In [ ]:
import pandas as pd

import numpy as np

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df.isnull())

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False


In [ ]:
import pandas as pd

import numpy as np

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(dict)

print(df.fillna(0))

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0


In [ ]:
import pandas as pd

import numpy as np

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}

df = pd.DataFrame(dict)

print(df)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0


In [ ]:
import pandas as pd

import numpy as np

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

print(df.dropna())

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0


In [ ]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}


df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98


In [ ]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object



In [ ]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98


In [ ]:
columns = list(df)

for i in columns:
    print (df[i][2])

sudhir
M.Tech
80


In [ ]:
FUNCTION	DESCRIPTION
index()	Method returns index (row labels) of the DataFrame
insert()	Method inserts a column into a DataFrame
add()	Method returns addition of dataframe and other, element-wise (binary operator add)
sub()	Method returns subtraction of dataframe and other element-wise (binary operator sub)
mul()	Method returns multiplication of dataframe and other, element-wise (binary operator mul)
div()	Method returns floating division of dataframe and other element-wise (binary operator truediv)
unique()	Method extracts the unique values in the dataframe
nunique()	Method returns count of the unique values in the dataframe
value_counts()	Method counts the number of times each unique value occurs within the Series
columns()	Method returns the column labels of the DataFrame
axes()	Method returns a list representing the axes of the DataFrame
isnull()	Method creates a Boolean Series for extracting rows with null values
notnull()	Method creates a Boolean Series for extracting rows with non-null values
isin()	Method extracts rows from a DataFrame where a column value exists in a predefined collection
dtypes()	Method returns a Series with the data type of each column. The result’s index is the original DataFrame’s columns
astype()	Method converts the data types in a Series
values()	Method returns a Numpy representation of the DataFrame i.e only the values in the DataFrame will be returned, the axes labels will be removed
sort_values()	Method sorts a data frame in Ascending or Descending order of passed Column
sort_index()	Method sorts the values in a DataFrame based on their index positions or labels instead of their values but sometimes a data frame is made out of two or more data frames and hence later index can be changed using this method
loc[]	Method retrieves rows based on index label
iloc[]	Method retrieves rows based on index position
ix[]	Method retrieves DataFrame rows based on either index label or index position. This method combines the best features of the .loc[] and .iloc[] methods
rename()	Method is called on a DataFrame to change the names of the index labels or column names
drop()	Method is used to delete rows or columns from a DataFrame
pop()	Method is used to delete rows or columns from a DataFrame
sample()	Method pulls out a random sample of rows or columns from a DataFrame
nsmallest()	Method pulls out the rows with the smallest values in a column
nlargest()	Method pulls out the rows with the largest values in a column
shape()	Method returns a tuple representing the dimensionality of the DataFrame
ndim()	Method returns an ‘int’ representing the number of axes / array dimensions.
Returns 1 if Series, otherwise returns 2 if DataFrame
dropna()	Method allows the user to analyze and drop Rows/Columns with Null values in different ways
fillna()	Method manages and let the user replace NaN values with some value of their own
rank()	Values in a Series can be ranked in order with this method
query()	Method is an alternate string-based syntax for extracting a subset from a DataFrame
copy()	Method creates an independent copy of a pandas object
duplicated()	Method creates a Boolean Series and uses it to extract rows that have duplicate values
drop_duplicates()	Method is an alternative option to identifying duplicate rows and removing them through filtering
set_index()	Method sets the DataFrame index (row labels) using one or more existing columns
reset_index()	Method resets index of a Data Frame. This method sets a list of integer ranging from 0 to length of data as index
where()	Method is used to check a Data Frame for one or more condition and return the result accordingly. By default, the rows not satisfying the condition are filled with NaN value

In [ ]:
taskoftheday = {
    "dayactivity": ["exercise", "bath", "medicine", "puja", "facewash", "diery"],
    "progress": [1, 1, 1, 0, 1, "ok"]
}

dataframe = pd.DataFrame(taskoftheday)
print(dataframe)

  dayactivity progress
0    exercise        1
1        bath        1
2    medicine        1
3        puja        0
4    facewash        1
5       diery       ok


In [ ]:
abc = [['exercise',1],['bath',1],['medicine',1]]

df = pd.DataFrame(abc,['a','b','c'],columns = ['dayactivity','progress'])
df

dayactivity  progress
a    exercise         1
b        bath         1
c    medicine         1

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('index').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('dayactivity').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['progress']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'progress'}, axis=1)
              .sort_values('progress', ascending=True))
  xs = counted['progress']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values('progress', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('index')):
  _plot_series(series, series_name, i)
  fig.legend(title='index', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('progress')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['progress']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'progress'}, axis=1)
              .sort_values('progress', ascending=True))
  xs = counted['progress']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('progress', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('dayactivity')):
  _plot_series(series, series_name, i)
  fig.legend(title='dayactivity', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('progress')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['dayactivity'].value_counts()
    for x_label, grp in _df_4.groupby('index')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('index')
_ = plt.ylabel('dayactivity')

In [ ]:
data = {'one' : pd.Series([1, 2, 3, 4]),
        'two' : pd.Series([10, 20, 30, 40]),
        'three' : pd.Series([100, 200, 300, 400]),
        'four' : pd.Series([1000, 2000, 3000, 4000])}

df = pd.DataFrame(data)
df

one  two  three  four
0    1   10    100  1000
1    2   20    200  2000
2    3   30    300  3000
3    4   40    400  4000

In [ ]:
df.iloc[1:3,1:3]

two  three
1   20    200
2   30    300

In [ ]:
df.loc[1:3,'two':'four']

two  three  four
1   20    200  2000
2   30    300  3000
3   40    400  4000

In [ ]:
import pandas as pd
data = {
    "Name": ["Ansh", "Sahil", "Ram"],
    "Age": [21, 20, 41],
    "City": ["Moradabad", "New Delhi", "Chennai"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age       City
0   Ansh   21  Moradabad
1  Sahil   20  New Delhi
2    Ram   41    Chennai


In [ ]:
import pandas as pd

names = ["Akshit", "Uday", "Sam"]
ages = [25, 30, 35]
cities = ["Gurugram", "New Delhi", "Chicago"]

df = pd.DataFrame({
    "Name": names,
    "Age": ages,
    "City": cities
})

print(df)

     Name  Age       City
0  Akshit   25   Gurugram
1    Uday   30  New Delhi
2     Sam   35    Chicago


In [ ]:
import pandas as pd

data = {"Name": ["Eve", "Jack", "Charlie", "Henry", "John"],
        "Age": [25, 30, 35, 40, 45],
        "City": ["NY", "LA", "SF", "Houston", "Seattle"]}
df = pd.DataFrame(data)

print(df.head(3))

print()

print(df.tail(2))

      Name  Age City
0      Eve   25   NY
1     Jack   30   LA
2  Charlie   35   SF

    Name  Age     City
3  Henry   40  Houston
4   John   45  Seattle


In [ ]:
print(df.columns)

Index(['Name', 'Age', 'City'], dtype='object')


In [ ]:
print(df.dtypes)

Name    object
Age      int64
City    object
dtype: object


In [ ]:
print(df.describe())

             Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000


In [ ]:
print(df["Name"])

0        Eve
1       Jack
2    Charlie
3      Henry
4       John
Name: Name, dtype: object


In [ ]:
print(df[["Name", "City"]])

      Name     City
0      Eve       NY
1     Jack       LA
2  Charlie       SF
3    Henry  Houston
4     John  Seattle


In [ ]:
print(df["City"].unique())

['NY' 'LA' 'SF' 'Houston' 'Seattle']


In [ ]:
print(df[df["Age"] > 30])

      Name  Age     City
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle


In [ ]:
print(df.iloc[0])

Name    Eve
Age      25
City     NY
Name: 0, dtype: object


In [ ]:
print(df.iloc[0, 2])

NY


In [ ]:
print(df.iloc[1:3])

      Name  Age City
1     Jack   30   LA
2  Charlie   35   SF


In [ ]:
df.set_index("Name", inplace=True)

In [ ]:
print(df.loc["Alice"])

KeyError: 'Alice'

In [ ]:
#Modifying Data in Pandas
import pandas as pd

data = {'Name': ['Eve', 'Jack', 'Charlie', 'Henry', 'John'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['NY', 'LA', 'SF', 'Houston', 'Seattle']}
df = pd.DataFrame(data)
df

Name  Age     City
0      Eve   25       NY
1     Jack   30       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('City').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Age']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Age'}, axis=1)
              .sort_values('Age', ascending=True))
  xs = counted['Age']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Age', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Age')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Age']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Age'}, axis=1)
              .sort_values('Age', ascending=True))
  xs = counted['Age']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Age', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('City')):
  _plot_series(series, series_name, i)
  fig.legend(title='City', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Age')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['City'].value_counts()
    for x_label, grp in df.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('City')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['City'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='City', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.loc[df['Name'] == 'Jack', 'Age'] = 42

print(df)

      Name  Age     City
0      Eve   25       NY
1     Jack   42       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle


In [ ]:
df['City'] = ['Boston', 'Chicago', 'LA', 'Austin', 'Miami']
df

Name  Age     City
0      Eve   25   Boston
1     Jack   42  Chicago
2  Charlie   35       LA
3    Henry   40   Austin
4     John   45    Miami

In [ ]:
df.loc[df['City'] == 'LA', 'Age'] = 31
df


Name  Age     City
0      Eve   25   Boston
1     Jack   42  Chicago
2  Charlie   31       LA
3    Henry   40   Austin
4     John   45    Miami

In [ ]:
# Removing Data in Pandas
import pandas as pd

data = {'Name': ['Eve', 'Jack', 'Charlie', 'Henry', 'John'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['NY', 'LA', 'SF', 'Houston', 'Seattle']}
df = pd.DataFrame(data)

print(df)

      Name  Age     City
0      Eve   25       NY
1     Jack   30       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle


In [ ]:
df = df.drop('City', axis=1)
print(df)

      Name  Age
0      Eve   25
1     Jack   30
2  Charlie   35
3    Henry   40
4     John   45


In [ ]:
df = df.drop(2, axis=0)
print(df)


    Name  Age
0    Eve   25
1   Jack   30
3  Henry   40
4   John   45


In [ ]:
df = df[df['Age'] != 35]
print(df)

    Name  Age
0    Eve   25
1   Jack   30
3  Henry   40
4   John   45


In [ ]:
df = pd.DataFrame(data)

del df

In [ ]:
#finding missing value
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False


In [ ]:
#Filtering Data Based on Missing Values
#import pandas as pd
#d = pd.read_csv(".csv")

#bool_series = pd.isnull(d["Gender"])
#missing_gender_data = d[bool_series]
#print(missing_gender_data)

FileNotFoundError: [Errno 2] No such file or directory: '/content/employees.csv'

In [ ]:
import pandas as pd
import numpy as np

data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False


In [ ]:
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

nmv = df.notnull()

print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True


In [ ]:
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [ ]:
df.fillna(method='pad')

/tmp/ipython-input-196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')


First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [ ]:
df.fillna(method='bfill')

/tmp/ipython-input-2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [ ]:
import pandas as pd

df = pd.DataFrame({"A": [12, 4, 5, None, 1],
                   "B": [None, 2, 54, 3, None],
                   "C": [20, 16, None, 3, 8],
                   "D": [14, 3, None, None, 6]})
print(df)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0


In [ ]:
products = ['A','B','C','D']
products

['A', 'B', 'C', 'D']

In [ ]:
type(products)

list

In [ ]:
product_categories = pd.Series(products)
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [ ]:
type(product_categories)

pandas.core.series.Series

In [ ]:
type(pd.Series(products))

pandas.core.series.Series

In [ ]:
daily_rates_dollars = pd.Series([40, 45, 50, 60])
daily_rates_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [ ]:
print(daily_rates_dollars)

0    40
1    45
2    50
3    60
dtype: int64


In [ ]:
import numpy as np

In [ ]:
array_a = np.array([10, 20, 30, 40, 50])
array_a

array([10, 20, 30, 40, 50])

In [ ]:
type(array_a)

numpy.ndarray

NameError: name 'series_a' is not defined

In [ ]:
daily_rates_dollars = pd.Series([40, 45, 50, 60])
daily_rates_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [ ]:
daily_rates_dollars.dtype

dtype('int64')

In [ ]:
daily_rates_dollars.size

4

In [ ]:
type(daily_rates_dollars.size)

int

In [ ]:
print(daily_rates_dollars.name)

None


In [ ]:
daily_rates_dollars.name = "product"
daily_rates_dollars

0    40
1    45
2    50
3    60
Name: product, dtype: int64

In [ ]:
daily_rates_dollars.name

'product'

In [ ]:
print(daily_rates_dollars.name)

product


In [ ]:
prices_per_category = {'Product A': 1234,'Product B': 4444,'Product C': 3333}
prices_per_category

{'Product A': 1234, 'Product B': 4444, 'Product C': 3333}

In [ ]:
type(prices_per_category)

dict

In [ ]:
prices_per_category.index

AttributeError: 'dict' object has no attribute 'index'

In [ ]:
#indexing type 1. lebel based, 2. position based


In [ ]:
series_a = pd.Series([10, 20, 30, 40, 50])
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
series_a.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
type(series_a.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
list(series_a.index)

[0, 1, 2, 3, 4]

In [ ]:
prices_per_category = {'Product A': 1234,'Product B': 4444,'Product C': 3333}
prices_per_category

{'Product A': 1234, 'Product B': 4444, 'Product C': 3333}

In [ ]:
prices_per_category.index


AttributeError: 'dict' object has no attribute 'index'

In [ ]:
type(prices_per_category.index)

AttributeError: 'dict' object has no attribute 'index'

In [ ]:
series_a = pd.Series([10, 20, 30, 40, 50])
prices_per_category = pd.Series({'Product A': 1234,'Product B': 4444,'Product C': 3333})

In [ ]:
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
series_a[0]

np.int64(10)

In [ ]:
prices_per_category

Product A    1234
Product B    4444
Product C    3333
dtype: int64

In [ ]:
prices_per_category['Product A']

np.int64(1234)

In [ ]:
prices_per_category[1]

/tmp/ipython-input-2333564195.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prices_per_category[1]


np.int64(4444)

In [ ]:
series_b = pd.Series([10, 20, 30, 40, 50], index = [1, 2, 3, 4, 5])
series_b

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [ ]:
series_b[1]

np.int64(10)

In [ ]:
series_c = pd.Series([10, 20, 30, 40, 50], index = ["1", "2", "3", "4", "5"])
series_c

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [ ]:
series_c[1]

/tmp/ipython-input-2194739140.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_c[1]


np.int64(20)

In [ ]:
series_c["1"]

np.int64(10)

In [ ]:
prices_per_category

Product A    1234
Product B    4444
Product C    3333
dtype: int64

In [1]:
import pandas as pd

In [2]:
start_date_deposits = pd.Series({
    '4/1/2014'  : 2000,
    '2/3/2019'  : 2000,
    '23/12/2013': 2000,
    '9/8/2015'  : 2000,
    '4/9/2017'  : 2000,
    '23/5/2020' : 2000,
    })

In [3]:
start_date_deposits

4/1/2014      2000
2/3/2019      2000
23/12/2013    2000
9/8/2015      2000
4/9/2017      2000
23/5/2020     2000
dtype: int64

In [4]:
start_date_deposits.sum

<bound method Series.sum of 4/1/2014      2000
2/3/2019      2000
23/12/2013    2000
9/8/2015      2000
4/9/2017      2000
23/5/2020     2000
dtype: int64>

In [5]:
start_date_deposits.sum()

np.int64(12000)

In [6]:
start_date_deposits.min()

2000

In [7]:
start_date_deposits.max()

2000

In [8]:
start_date_deposits.idxmax()

'4/1/2014'

In [9]:
start_date_deposits.idxmin()

'4/1/2014'

In [10]:
start_date_deposits.head()

4/1/2014      2000
2/3/2019      2000
23/12/2013    2000
9/8/2015      2000
4/9/2017      2000
dtype: int64

In [11]:
start_date_deposits.tail()

2/3/2019      2000
23/12/2013    2000
9/8/2015      2000
4/9/2017      2000
23/5/2020     2000
dtype: int64

In [13]:
start_date_deposits.head(3)

4/1/2014      2000
2/3/2019      2000
23/12/2013    2000
dtype: int64

In [14]:
start_date_deposits.head(n=4)

4/1/2014      2000
2/3/2019      2000
23/12/2013    2000
9/8/2015      2000
dtype: int64

In [15]:
#constructing dataframe from scratch
# dataframe from a dictionary of lists

data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice': [12312, 34567, 34333]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         12312
1   Product B         34567
2   Product C         34333

from matplotlib import pyplot as plt
df['ProductPrice'].plot(kind='hist', bins=20, title='ProductPrice')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('ProductName').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['ProductPrice'].plot(kind='line', figsize=(8, 4), title='ProductPrice')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['ProductName'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='ProductPrice', y='ProductName', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [16]:
# dictionary list + specify an index
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice': [12312, 34567, 34333]}
df = pd.DataFrame(data, index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         12312
B   Product B         34567
C   Product C         34333

In [17]:
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice': [12312, 34567, 34333]}
product_IDs = ['A', 'B', 'C']
df = pd.DataFrame(data, index = product_IDs)
df

ProductName  ProductPrice
A   Product A         12312
B   Product B         34567
C   Product C         34333

In [19]:
#construct A dataframe from a list of dictionaries
data = [{'ProductName': 'Product A', 'ProductPrice': 12345},
        {'ProductName': 'Product B', 'ProductPrice': 22333},
        {'ProductName': 'Product C', 'ProductPrice': 33333}]
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         12345
1   Product B         22333
2   Product C         33333

In [21]:
#Construct a Dataframe from a dictionary of pandas Series
ser_products = pd.Series(['Product A', 'Product B', 'Product C'])
ser_prices = pd.Series([12345, 22333, 33333])
data = {'ProductName': ser_products, 'ProductPrice': ser_prices}
df = pd.DataFrame(data)
df


ProductName  ProductPrice
0   Product A         12345
1   Product B         22333
2   Product C         33333

In [22]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'], index =['A', 'B', 'C'])
ser_prices = pd.Series([12345, 22333, 33333], index = ['A', 'B', 'C'])
data = {'ProductName': ser_products, 'ProductPrice': ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
A   Product A         12345
B   Product B         22333
C   Product C         33333

In [23]:
#dataframe from a list of lists
data = [['Product A', 12345], ['Product B', 22333], ['Product C', 33333]]
df = pd.DataFrame(data)
df

0      1
0  Product A  12345
1  Product B  22333
2  Product C  33333

In [24]:
df.colummns = ['ProductName', 'ProductPrice']
df

/tmp/ipython-input-765801716.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colummns = ['ProductName', 'ProductPrice']


0      1
0  Product A  12345
1  Product B  22333
2  Product C  33333

In [25]:
df.index = ['A', 'B', 'C']
df

0      1
A  Product A  12345
B  Product B  22333
C  Product C  33333

In [26]:
#dataframe in a profrssional way
# its data
# its columns
# its index


In [28]:
df= pd.DataFrame(data = [['Product A', 213344], ['Product B', 546667], ['Product C', 123456]],
                 columns = ['ProductName', 'ProductPrice'],
                 index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A        213344
B   Product B        546667
C   Product C        123456

In [29]:
df.shape

(3, 2)